version: "3.8"
services: 
  postgresql:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=P@ssword
    networks: 
      - local 
  sqlserver:
   container_name: sqlserver
   hostname: sqlserver
   image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
   restart: always
   volumes: 
    - type: volume
      source: mssql
      target: /var/opt/mssql
   environment: 
    - ACCEPT_EULA=Y
    - SA_PASSWORD=P@ssword
   ports: 
    - "1433:1433"
   networks: 
     - local 
  rabbitmq:
   container_name: rabbitmq
   hostname: rabbitmq
   image: rabbitmq:3.8.9-management
   restart: always
   volumes:
    - type: volume
      source: rabbitmq
      target: /var/lib/rabbitmq
   environment: 
    - RABBITMQ_DEFAULT_USER=sa
    - RABBITMQ_DEFAULT_PASS=P@ssword
   ports:
    - 15672:15672
    - 5672:5672
   networks: 
     - local 
  redis:
   container_name: redis
   hostname: redis
   image: "redis:6.0.8"
   ports:
    - "6379:6379"
   restart: always 
   volumes:
    - type: volume
      source: redis-data
      target: /data
    - type: volume
      source: redis-usr-conf
      target: /usr/local/etc/redis/redis.conf
   networks: 
     - local 
volumes: 
  mssql:
  postgresql:
  rabbitmq:
  redis-usr-conf:
  redis-data:
networks: 
  local:
    driver: bridge

