version: "3.8"
services: 
  local-mssql:
   container_name: Local-MsSql
   image: microsoft/mssql-server-linux:2017-CU13
   restart: always
   volumes: 
    - local-mssql-server-linux-data:/var/opt/mssql/data
   environment: 
    - ACCEPT_EULA=Y
    - SA_PASSWORD=P@ssword
   ports: 
    - "1434:1433"
  local-rabbitmq:
   container_name: Local_RabbitMq
   image: rabbitmq:3.8.9-management
   restart: always
   volumes:
    - local-rabitmq:/var/lib/rabbitmq
   hostname: rabbitmq
   environment: 
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=P@ssword
   ports:
    - 15672:15672
    - 5672:5672
  local-redis:
   container_name: Local_Redis
   image: "redis:6.0.8"
   hostname: redis
   ports:
    - "6379:6379"
   restart: always 
   volumes:
    - local-redis-usr-conf:/usr/local/etc/redis/redis.conf
    - local-redis-data:/data
volumes: 
  local-mssql-server-linux-data:
  local-redis-usr-conf:
  local-redis-data:
  local-rabitmq:
