version: "3.8"
services: 
  sqlserver:
   container_name: sqlserver
   hostname: sqlserver
   image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
   restart: always
   volumes: 
    - type: volume
      source: mssql
      target: /var/opt/mssql
   environment: 
    - ACCEPT_EULA=Y
    - SA_PASSWORD=P@ssword
   ports: 
    - "1433:1433"
  rabbitmq:
   container_name: rabbitmq
   hostname: rabbitmq
   image: rabbitmq:3.8.9-management
   restart: always
   volumes:
    - type: volume
      source: rabbitmq
      target: /var/lib/rabbitmq
   environment: 
    - RABBITMQ_DEFAULT_USER=sa
    - RABBITMQ_DEFAULT_PASS=P@ssword
   ports:
    - 15672:15672
    - 5672:5672
  redis:
   container_name: redis
   hostname: redis
   image: "redis:6.0.8"
   ports:
    - "6379:6379"
   restart: always 
   volumes:
    - type: volume
      source: redis-data
      target: /data
    - type: volume
      source: redis-usr-conf
      target: /usr/local/etc/redis/redis.conf
volumes: 
  mssql:
  rabbitmq:
  redis-usr-conf:
  redis-data:

